version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: twitcord_local_django
    container_name: twitcord_django
    depends_on:
      - postgres
    volumes:
      - ./twitcord_Back:/app:z
    env_file:
      - ./twitcord_Back/.envs/.local/.django
      - ./twitcord_Back/.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: twitcord_production_postgres
    container_name: twitcord_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./twitcord_Back/.envs/.local/.postgres
  
  react:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    image: twitcord_local_react
    container_name: twitcord_react
    volumes:
      - ./twitcord_front:/app:z
      - /app/node_modules
    ports:
      - "3000:3000"



