export const ActionTypes = {
  SET_SIGN_UP_INFO: 'SET_SIGN_UP_INFO',
  SET_LOG_IN_INFO: 'SET_LOG_IN_INFO',
  SET_TWEET_TEXT: 'SET_TWEET_TEXT',
  SET_SNACKBAR_STATE: 'SET_SNACKBAR_STATE',
<<<<<<< HEAD
  SET_USER_SEARCH_RESULT: 'SET_USER_SEARCH_RESULT',
=======
  SET_PROFILE_INFO: 'SET_PROFILE_INFO',
  SET_USER_GENERAL_INFO: 'SET_USER_GENERAL_INFO',
>>>>>>> c561fe336b74d07327206e2930b781daada91765
};

