export const ActionTypes = {
  SET_SIGN_UP_INFO: 'SET_SIGN_UP_INFO',
  SET_LOG_IN_INFO: 'SET_LOG_IN_INFO',
  SET_TWEET_TEXT: 'SET_TWEET_TEXT',
  SET_SNACKBAR_STATE: 'SET_SNACKBAR_STATE',
  SET_TWEET_LIST_INFO: 'SET_TWEET_LIST_INFO',
};

