export const ActionTypes = {
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_REQUEST_FAILURE: 'SIGN_UP_REQUEST_FAILURE',
  SIGN_UP_REQUEST_SUCCESS: 'SIGN_UP_REQUEST_SUCCESS',
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  LOG_IN_REQUEST_FAILURE: 'LOG_IN_REQUEST_FAILURE',
  LOG_IN_REQUESR_SUCCESS: 'LOG_IN_REQUESR_SUCCESS',
};

