# Generated by Django 3.1.7 on 2021-03-18 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
