# Generated by Django 3.1.7 on 2021-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0003_tweet_create_date_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitcorduser',
            name='bio',
            field=models.TextField(default=None, max_length=76),
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='first_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='last_name',
            field=models.TextField(default=None),
        ),
    ]
