# Generated by Django 3.1.7 on 2021-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0004_auto_20210416_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitcorduser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='twitcorduser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
