# Generated by Django 3.1.7 on 2021-04-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0005_auto_20210416_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitcorduser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='first_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
