# Generated by Django 3.1.7 on 2021-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitcorduser',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='twitcorduser',
            name='has_profile_img',
            field=models.BooleanField(default=False),
        ),
    ]
