# Generated by Django 3.1.7 on 2021-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0007_auto_20210416_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitcorduser',
            name='bio',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitcorduser',
            name='username',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
