# Generated by Django 3.1.7 on 2021-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitcord_app', '0008_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitcorduser',
            name='has_header_img',
            field=models.BooleanField(default=False),
        ),
    ]
